spring.application.name=travel-log-backend

# Pripojeni k MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/travel_log_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=travellog-2026

# Hibernate - Automaticke upravy schematu
spring.jpa.hibernate.ddl-auto=update

# Ladeni a logovani SQL v konzoli
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MONITORING (Actuator)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# LOGOVANI
logging.level.cz.upa.travellogbackend=INFO
logging.file.name=logs/travel-log.log

# Format logu
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n